windowrule {
  name = obsidian_focus_on_clip
  match:class = obsidian
  focus_on_activate = on
}

windowrule {
  name = steam
  match:class = steam
  float = on
}

windowrule {
  name = exe
  match:class = *.exe
  float = on
}

windowrule {
  name = steamapps
  match:class = steam_app_*
  fullscreen = on
  immediate = yes
  float = on
}
