#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")/.." && pwd)"
THEME="${1:-catppuccin}"
COLORS="$DOTFILES/themes/$THEME/colors.toml"

if [[ ! -f "$COLORS" ]]; then
  echo "Theme '$THEME' not found at $COLORS"
  exit 1
fi

# Parse colors.toml into an associative array
declare -A c
while IFS='=' read -r key val; do
  key="$(echo "$key" | xargs)"
  val="$(echo "$val" | xargs | tr -d '"')"
  [[ -z "$key" || "$key" == \#* ]] && continue
  c["$key"]="$val"
done < "$COLORS"

# Helper: strip # from hex
hex() { echo "${1#\#}"; }

echo "Building theme: $THEME"

# --- Waybar CSS ---
cat > "$DOTFILES/waybar/.config/waybar/colors.css" <<EOF
/* Generated by themes/build.sh ($THEME) */
@define-color accent ${c[accent]};
@define-color accent_secondary ${c[accent_secondary]};
@define-color warning ${c[warning]};
@define-color error ${c[error]};
@define-color success ${c[success]};
@define-color info ${c[info]};

@define-color text ${c[foreground]};
@define-color text_dim ${c[foreground_dim]};
@define-color text_muted ${c[foreground_muted]};

@define-color base ${c[background]};
@define-color mantle ${c[background_alt]};
@define-color crust ${c[background_dark]};
@define-color surface ${c[surface]};
@define-color surface_bright ${c[surface_bright]};
@define-color overlay ${c[overlay]};
EOF

# --- Yazi ---
cat > "$DOTFILES/yazi/.config/yazi/theme.toml" <<EOF
# Generated by themes/build.sh ($THEME)

[mgr]
cwd = { fg = "${c[accent]}" }

find_keyword = { fg = "${c[warning]}", bold = true }
find_position = { fg = "${c[accent_secondary]}", italic = true }

marker_copied = { fg = "${c[success]}", bg = "${c[success]}" }
marker_cut = { fg = "${c[error]}", bg = "${c[error]}" }
marker_marked = { fg = "${c[accent]}", bg = "${c[accent]}" }
marker_selected = { fg = "${c[accent_secondary]}", bg = "${c[accent_secondary]}" }

symlink_target = { fg = "${c[foreground_muted]}", italic = true }

border_symbol = "│"
border_style = { fg = "${c[surface_bright]}" }

count_copied = { fg = "${c[background]}", bg = "${c[success]}" }
count_cut = { fg = "${c[background]}", bg = "${c[error]}" }
count_selected = { fg = "${c[background]}", bg = "${c[accent_secondary]}" }

[mode]
normal_main = { fg = "${c[background]}", bg = "${c[accent]}", bold = true }
normal_alt = { fg = "${c[accent]}", bg = "${c[surface]}" }

select_main = { fg = "${c[background]}", bg = "${c[accent_secondary]}", bold = true }
select_alt = { fg = "${c[accent_secondary]}", bg = "${c[surface]}" }

unset_main = { fg = "${c[background]}", bg = "${c[error]}", bold = true }
unset_alt = { fg = "${c[error]}", bg = "${c[surface]}" }

[status]
overall = { fg = "${c[foreground]}", bg = "${c[background]}" }

sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

perm_type = { fg = "${c[accent]}" }
perm_read = { fg = "${c[success]}" }
perm_write = { fg = "${c[error]}" }
perm_exec = { fg = "${c[warning]}" }
perm_sep = { fg = "${c[surface_bright]}" }

progress_label = { fg = "${c[foreground]}", bold = true }
progress_normal = { fg = "${c[accent]}", bg = "${c[surface]}" }
progress_error = { fg = "${c[error]}", bg = "${c[surface]}" }

[input]
border = { fg = "${c[accent]}" }
title = {}
value = {}
selected = { reversed = true }

[cmp]
border = { fg = "${c[accent]}" }
active = { fg = "${c[accent_secondary]}", bold = true }
inactive = {}

[tasks]
border = { fg = "${c[accent]}" }
title = {}
hovered = { fg = "${c[accent]}", underline = true }

[which]
cols = 3
mask = { bg = "${c[surface]}" }
cand = { fg = "${c[accent]}" }
rest = { fg = "${c[foreground_muted]}" }
desc = { fg = "${c[foreground]}" }
separator = "  "
separator_style = { fg = "${c[surface_bright]}" }

[filetype]
rules = [
  # Media
  { mime = "image/*", fg = "${c[warning]}" },
  { mime = "video/*", fg = "${c[accent_secondary]}" },
  { mime = "audio/*", fg = "${c[accent_secondary]}" },

  # Archives
  { mime = "application/zip", fg = "${c[error]}" },
  { mime = "application/gzip", fg = "${c[error]}" },
  { mime = "application/x-tar", fg = "${c[error]}" },
  { mime = "application/x-bzip*", fg = "${c[error]}" },
  { mime = "application/x-xz", fg = "${c[error]}" },
  { mime = "application/x-7z-compressed", fg = "${c[error]}" },
  { mime = "application/x-rar", fg = "${c[error]}" },

  # Fallbacks
  { url = "*/", fg = "${c[accent]}" },
  { is = "orphan", fg = "${c[error]}" },
  { is = "link", fg = "${c[info]}" },
  { is = "exec", fg = "${c[success]}" },
]
EOF

# --- Foot ---
cat > "$DOTFILES/foot/.config/foot/theme.ini" <<EOF
# Generated by themes/build.sh ($THEME)

[colors-dark]
alpha=0.9
foreground=$(hex "${c[foreground]}")
background=$(hex "${c[background]}")
regular0=$(hex "${c[color0]}")
regular1=$(hex "${c[color1]}")
regular2=$(hex "${c[color2]}")
regular3=$(hex "${c[color3]}")
regular4=$(hex "${c[color4]}")
regular5=$(hex "${c[color5]}")
regular6=$(hex "${c[color6]}")
regular7=$(hex "${c[color7]}")
bright0=$(hex "${c[color8]}")
bright1=$(hex "${c[color9]}")
bright2=$(hex "${c[color10]}")
bright3=$(hex "${c[color11]}")
bright4=$(hex "${c[color12]}")
bright5=$(hex "${c[color13]}")
bright6=$(hex "${c[color14]}")
bright7=$(hex "${c[color15]}")
EOF

echo "Done. Generated theme files for: waybar, yazi, foot"
