source = ./theme.conf

monitor=DP-2,preferred,auto,1

input {
  kb_layout = hr
  kb_variant = us
  follow_mouse = 1
  sensitivity = 0
  accel_profile = flat
}

general {
  gaps_in = 4
  gaps_out = 8
  border_size = 2
  col.active_border = $border_active
  col.inactive_border = $border_inactive
  layout = dwindle
  allow_tearing = true
}

xwayland {
  force_zero_scaling = true
}

decoration {
  rounding = 4
  blur {
    enabled = false
  }
}

animations {
  enabled = true
  bezier = myBezier, 0.12, 0.9, 0.3, 1.1
  animation = windows, 1, 1, myBezier
  animation = windowsOut, 1, 1, default, popin 90%
  animation = border, 1, 1, default
  animation = borderangle, 1, 1, default
  animation = fade, 1, 1, default
  animation = workspaces, 1, 1, default
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_status = master
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  vfr = true
  vrr = true
}

workspace = 1, name:1:
workspace = 2, name:2:
workspace = 3, name:3:
workspace = 4, name:4:
workspace = 5, name:5:
workspace = 6, name:6:
workspace = 7, name:7:
workspace = 8, name:8:
workspace = 9, name:9:
workspace = 10, name:0:

source = ./hyprland/keys.conf
source = ./hyprland/autostart.conf
source = ./hyprland/windowrules.conf
